# Attempt to set a double value.

# The double value to use.
float64 value

---

# Whether or not the attempt was successful. If this is false, the message
# should explain the error.
bool success

# Informational message.
string message
