# Attempt to set a string value.

# The string value to use.
string value

---

# Whether or not the attempt was successful. If this is false, the message
# should explain the error.
bool success

# Informational message.
string message
